name: advanced_datatable
description: An addtion to the Flutter PaginatedDataTable allowing pagination
  also for the datasource aka server side datatables
version: 0.0.8
homepage: https://devowl.de

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
